<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $title_for_layout; ?></title>

        <!-- META TAGS -->
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <?php
        if ($pluginName) {
            echo $this->Html->css("x_style");
            echo $this->Html->css("empresas/Companies");
            echo $this->fetch('css');

            echo $this->Html->script('jqueryTunado');
            echo $this->Html->script('jquery.roundabout.min.js');
            echo $this->Html->script('jquery-ui-1.9.1.custom.min');
            echo $this->Html->script('jquery.mask.min');
            echo $this->Html->script('javascript.lib');
            echo $this->Html->script('jquery.stringify');
            echo $this->Html->script('complete');
            echo $this->Html->script('jquery.cycle.all');
            echo $this->Html->script('jquery.jcarousel.min');
            echo $this->Html->script("empresas/Companies");
            echo $this->Html->script('refresh');
            echo $this->fetch('script');
        }
        ?>
        <style>
            .log{
                width: 9%;
                margin-top: -2px;
            }
        </style>
    </head>

    <body
        style="background: url('../img/docemel/background.jpg') fixed no-repeat; -webkit-background-size: cover; -o-background-size: cover; -moz-background-size: cover; background-size: cover;">
        <div style="width: 100%; height: 50px; background-color: #000; position: absolute; top: 0;">
            <img src="../img/docemel/logo.png" class="log"/>
        </div>	
        <?php echo $this->fetch('content'); ?>
    </body>
</html>

